meta_product_name: "Stalk_hub"
meta_title: "Stalk_hub - What can be found about you on social networks? Find out now!"
meta_description: "We live in a connected world. Many of us are present on social networks. With time, it can be difficult to keep track of what we leave lying around on the Internet. With stalk-hub, regain control of your image on the web!"
meta_image: "cover.jpg"
